app2/urls.py
from app2.views import *
from django.urls import path
app_name='python'

urlpatterns=[
    path('noori/',noori,name='noori'),
    path('baba/',baba,name='baba'),
]

app3/urls.py
from app3.views  import *
from django.urls import path
app_name='sql'
urlpatterns=[
    path('abhi/',abhi,name='abhi'),
    path('rizzu/',rizzu,name='rizzu'),
]

project15/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *
from app3.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('yashu/',yashu,name='yashu'),
    path('sadia/',sadia,name='sadia'),
    path('app2/',include('app2.urls')),
    path('app3/',include('app3.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here
def yashu(request):
    return render(request,'yashu.html') 

def sadia(request):
    return render(request,'sadia.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def noori(request):
    return render(request,'noori.html')

def baba(request):
    return render(request,'baba.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def abhi(request):
    return render(request,'abhi.html')

def rizzu(request):
    return render(request,'rizzu.html')

templates/abhi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>]
        <h1 style="color:pink;">it is abhi file</h1>
        <a href="{% url 'python:noori' %}">go to noori file(specific file app2)</a><br>
        <a href="{% url 'python:baba' %}">go to baba file(specific file app2)</a><br>
        <a href="{% url 'sql:rizzu' %}">go to rizzu file(specific file app3)</a><br>
        <a href="{% url 'yashu' %}">go to yashu file(generic file app1)</a><br>
        <a href="{% url 'sadia' %}">go to sadia file(generic file app1)</a><br>
    
    </center>
</body>
</html>

templates/baba.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color:red;">it is baba file</h1>
        <a href="{% url 'python:noori' %}">go to noori file(specific file app2)</a><br>
        <a href="{% url 'sql:abhi' %}">go to abhi file(specific file app3)</a><br>
        <a href="{% url 'sql:rizzu' %}">go to rizzu file(specific file app3)</a><br>
        <a href="{% url 'yashu' %}">go to yashu file(generic file app1)</a><br>
        <a href="{% url 'sadia' %}">go to sadia file(generic file app1)</a><br>
    
    </center>
</body>
</html>

templates/noori.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color:yellow;">it is noori file</h1>
        <a href="{% url 'python:baba' %}">go to baba file(specific file app2)</a><br>
        <a href="{% url 'sql:abhi' %}">go to abhi file(specific file app3)</a><br>
        <a href="{% url 'sql:rizzu' %}">go to rizzu file(specific file app3)</a><br>
        <a href="{% url 'yashu' %}">go to yashu file(generic file app1)</a><br>
        <a href="{% url 'sadia' %}">go to sadia file(generic file app1)</a><br>
    
    </center>
</body>
</html>

templates/rizzu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color:orange;">it is rizzu file</h1>
        <a href="{% url 'python:noori' %}">go to noori file(specific file app2)</a><br>
        <a href="{% url 'python:baba' %}">go to baba file(specific file app2)</a><br>
        <a href="{% url 'sql:abhi' %}">go to rizzu abhi (specific file app3)</a><br>
        <a href="{% url 'yashu' %}">go to yashu file(generic file app1)</a><br>
        <a href="{% url 'sadia' %}">go to sadia file(generic file app1)</a><br>

    </center>
</body>
</html>

templates/sadia.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color:blueviolet;">it is sadia file</h1>
        <a href="{% url 'yashu' %}">go to yashu file</a><br>
        <a href="{% url 'python:noori' %}">go to noori file(specific file app2)</a><br>
        <a href="{% url 'python:baba' %}">go to baba file(specific file app2)</a><br>
        <a href="{% url 'sql:abhi' %}">go to abhi file(specific file app3)</a><br>
        <a href="{% url 'sql:rizzu' %}">go to rizzu file(specific file app3)</a><br>
    
    </center>
</body>
</html>

templates/yashu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color:blueviolet;">it is yashu file</h1>
        <a href="{% url 'sadia' %}">go to sadia file</a><br>
        <a href="{% url 'python:noori' %}">go to noori file(specific file app2)</a><br>
        <a href="{% url 'python:baba' %}">go to baba file(specific file app2)</a><br>
        <a href="{% url 'sql:abhi' %}">go to abhi file(specific file app3)</a><br>
        <a href="{% url 'sql:rizzu' %}">go to rizzu file(specific file app3)</a><br>
    
    </center>
</body>
</html>